- name: print parameter
  hosts: localhost
  connection: local
  tasks:
    - name: print aq parameter
      ansible.builtin.debug:
        msg: parameter - {{ lookup('aws_ssm', 'dev.dev', region='us-east-1' ) }}

