- name: demo on play level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
     - name: Print URL
       ansible.builtin.debug:
          msg: URL - {{ URL }}

#demo on load vars from files
- name: load vars from  a file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}


  #Demo on task level
- name: demo on task level variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: task.example.com




