- name: demo on play level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
     - name: Print URL
       ansible.builtin.debug:
          msg: URL - {{ URL }}

  #Demo on task level
- name: demo on task level variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: task.example.com

#